site_name: setup_dev_environment
repo_url: https://github.com/hong539/setup_dev_environment
theme:
  name: material
  palette: 

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
dev_addr: '127.0.0.1:10000'