[tool.poetry]
name = "setup-dev-environment"
version = "0.1.0"
description = "prepare my dev enviroment on Linux"
authors = ["hong <yunghunghuang984@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
mkdocs-material = "^9.4.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
