#!/bin/sh

# Print out every line being run
set -x

# If a command fails, exit immediately.
set -e

USERNAME=${USERNAME:-"dev"}
HOME=${HOME:-"/home/$USERNAME"}
INSTALL_PATH=${INSTALL_PATH:-"/home/$USERNAME/.installed"}
CODESPACE=${CODESPACE:-"codespace"}
## APP VARS
APP_VERSION=${APP_VERSION:-"v0.14.0"}
APP_INSTALLER_SRC_FILENAME=${APP_INSTALLER_SRC_FILENAME:-"install.deb"}
APP_INSTALLER_DST_FILENAME=${APP_INSTALLER_DST_FILENAME:-"$APP_INSTALLER_SRC_FILENAME"}
APP_DST_PATH=${APP_DST_PATH:-"$HOME/.local/bin"}
# URL
DOWNLOAD_BASE_URL=${DOWNLOAD_BASE_URL:-""}

# Get File
curl -Lo "${INSTALL_PATH}/${APP_INSTALLER_DST_FILENAME}" "${DOWNLOAD_BASE_URL}/${APP_VERSION}/${APP_INSTALLER_SRC_FILENAME}"

# .deb files
sudo dpkg -i "${INSTALL_PATH}/${APP_INSTALLER_DST_FILENAME}" && sudo rm -f "${INSTALL_PATH}/${APP_INSTALLER_DST_FILENAME}"

# Archive Files
tar -xzf "${INSTALL_PATH}/${APP_INSTALLER_DST_FILENAME}" -C "${APP_DST_PATH}" && rm -f "${INSTALL_PATH}/${APP_INSTALLER_DST_FILENAME}"
chmod +x "${APP_DST_PATH}/"

exit 0